package:
  name: "qnt"
  version: "0.0.408"

source:
  path: .

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
  - pip
  - python >=3.10,<3.11
  - setuptools

  run:
    - scipy<=1.14.0
    - pandas=2.2.2
    - xarray<=2024.6.0
    - bottleneck=1.3.*
    - numpy<2.0
    - numba<=0.60.0
    - tabulate=0.9.*
    - python>=3.10,<3.11
    - progressbar2=3.*
    - cftime=1.6.*
    - plotly=5.22.*
    - matplotlib<=3.9.0
  #  - conda-forge::dash=2.17.*
  #  - conda-forge::python-avro=1.8.*
  #  - conda-forge::ta-lib
  #  - conda-forge::dash

about:
  license: MIT
  home: https://quantnet.ai