package:
  name: "toolbox"
  version: "0.0.179"

source:
  path: .

build:
  noarch: generic
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
  - pip
  - python=3.7.*
  - setuptools

  run:
    - scipy>=1.4.1
    - pandas=>1.0.1
    - xarray>=0.16.0
    - bottleneck>=1.3.1
    - numpy>=1.18
    - numba=0.47
    - tabulate>=0.8.3
    - python>=3.7
  #  - conda-forge::python-avro=1.8.*
  #  - quantnet::ta-lib

about:
  license: MIT
  home: https://quantiacs.io